language: python
python:
    - '2.7'
    - '3.5'
install:
    - pip install --upgrade pytest coverage codecov
    - pip install .
script:
    - coverage run --source MFQuery -m py.test
after_success:
    - codecov
